/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyCode;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javafx.stage.Stage;

import static main.Constants.*;


public class MineSweeper extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) {
        alertIncorrectInput.setTitle("Error");
        alertIncorrectInput.setHeaderText("Incorrect input");
        alertIncorrectInput.setContentText(incorrectInputText);
        greeting.setFill(Color.GREEN);
        greeting.setStyle("-fx-font-weight: bold");
        Group root = new Group();

        TextField col = new TextField();
        TextField row = new TextField();
        TextField amountMines = new TextField();
        col.setMaxSize(50,50);
        row.setMaxSize(50, 50);
        amountMines.setMaxSize(50, 50);

        VBox settings = new VBox();

        HBox colBox = new HBox();
        HBox rowBox = new HBox();
        HBox amountMinesBox = new HBox();
        colBox.getChildren().addAll(new Text("Columns"), col);
        rowBox.getChildren().addAll(new Text("Rows"), row);
        amountMinesBox.getChildren().addAll(new Text("Amount Mines"), amountMines);
        amountMinesBox.setSpacing(18);
        colBox.setSpacing(51);
        rowBox.setSpacing(70);

        settings.getChildren().addAll(greeting,colBox, rowBox, amountMinesBox);
        settings.setSpacing(5);
        settings.setStyle("-fx-font-weight: bold");

        root.getChildren().add(settings);

        Button accept = new Button("OK");
        Button cancel = new Button("Cancel");
        HBox buttons = new HBox();
        buttons.setAlignment(Pos.BOTTOM_RIGHT);
        buttons.getChildren().add(accept);
        buttons.getChildren().add(cancel);

        settings.getChildren().add(buttons);

        Scene scene = new Scene(root, WINDOW_WIDTH / 3.7, WINDOW_HEIGHT / 3.9);
        primaryStage.setScene(scene);
        primaryStage.setTitle("MineSweeper");
        primaryStage.getIcons().add(icon);
        primaryStage.setResizable(false);
        primaryStage.show();

        scene.setOnKeyPressed(event -> {
            if (event.getCode().equals(KeyCode.ENTER)) {
                accept.fire();
            }
            if (event.getCode().equals(KeyCode.ESCAPE)) {
                cancel.fire();
            }
        });

        accept.setOnAction(event -> {
            try {
                int intCol = Integer.parseInt(col.getText());
                int intRow = Integer.parseInt(row.getText());
                int intAmountMines = Integer.parseInt(amountMines.getText());
                new UI().start(primaryStage, intCol, intRow, intAmountMines);
                primaryStage.show();
            } catch (NumberFormatException e) {
                alertIncorrectInput.showAndWait();
            }
        });
        cancel.setOnAction(event -> primaryStage.close());
    }
}
