/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package Dinosaur.Game;


import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {
    @Override
    public void start (Stage primaryStage) throws Exception {
        BorderPane root = new BorderPane();//макет
        VBox vbox = new VBox(10);
        HBox hbox = new HBox(10);//10 - отступы между элементами, 10 пикселей
        hbox.setAlignment(Pos.CENTER);//выравнивание по центру

        Button btn1 = addButton("1");
        Button btn2 = addButton("2");
        Button btn3 = addButton("3");
        Button btn4 = addButton("4");
        Button btn5 = addButton("5");
        Button btn6 = addButton("6");

        vbox.getChildren().addAll(btn1, btn2, btn3);//добавили кнопки
        hbox.getChildren().addAll(btn4, btn5, btn6);

        root.setTop(hbox); // установили панели на макет
        root.setLeft(vbox);

        Scene scene = new Scene(root,300,250);//создаем сцену
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private Button addButton (String name) { //метод для создания кнопок, входной параметр - строка, которая будет на кнопки
        Button btn = new Button(name);
        btn.setPrefSize(70,20);
        return btn;
    }


    public static void main(String[] args) {//запускаем наше приложение
        launch(args);
    }

}
