/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programming.task3;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void test() {
        assertEquals(0, Main.obstacles.size());
    }


}
